//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses_Table()
        {
            this.Courses_Table1 = new HashSet<Courses_Table>();
            this.Offerd_course_table = new HashSet<Offerd_course_table>();
        }
    
        public int Courses_Id { get; set; }
        public int Program_ID { get; set; }
        public string Course_Code { get; set; }
        public string Course_Title_ { get; set; }
        public int Cr_Hrs { get; set; }
        public Nullable<int> Pre_requisite_id { get; set; }
        public string Semester_Number { get; set; }
        public int Course_Type_ID { get; set; }
    
        public virtual Course_Type_Table Course_Type_Table { get; set; }
        public virtual degree_programs degree_programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses_Table> Courses_Table1 { get; set; }
        public virtual Courses_Table Courses_Table2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offerd_course_table> Offerd_course_table { get; set; }
    }
}
