//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_regEntities : DbContext
    {
        public Online_regEntities()
            : base("name=Online_regEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course_Type_Table> Course_Type_Table { get; set; }
        public virtual DbSet<Courses_Table> Courses_Table { get; set; }
        public virtual DbSet<degree_programs> degree_programs { get; set; }
        public virtual DbSet<Department_Table> Department_Table { get; set; }
        public virtual DbSet<Offerd_course_table> Offerd_course_table { get; set; }
        public virtual DbSet<Registerd_courses_Table> Registerd_courses_Table { get; set; }
        public virtual DbSet<Remarks_Table> Remarks_Table { get; set; }
        public virtual DbSet<status_Table> status_Table { get; set; }
        public virtual DbSet<Students_Table> Students_Table { get; set; }
        public virtual DbSet<Teacher_Table> Teacher_Table { get; set; }
        public virtual DbSet<S_Courses_Table> S_Courses_Table { get; set; }
    }
}
