//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offerd_course_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offerd_course_table()
        {
            this.Registerd_courses_Table = new HashSet<Registerd_courses_Table>();
        }
    
        public int offered_course_Id { get; set; }
        public int Courses_Id { get; set; }
        public string Session { get; set; }
        public int Teacher_ID { get; set; }
    
        public virtual Courses_Table Courses_Table { get; set; }
        public virtual Teacher_Table Teacher_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registerd_courses_Table> Registerd_courses_Table { get; set; }
    }
}
