//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registerd_courses_Table
    {
        public int reg_crs_id { get; set; }
        public int offered_course_Id { get; set; }
        public int status_Id { get; set; }
        public int Remark_Id { get; set; }
        public int std_id { get; set; }
    
        public virtual Offerd_course_table Offerd_course_table { get; set; }
        public virtual Remarks_Table Remarks_Table { get; set; }
        public virtual status_Table status_Table { get; set; }
        public virtual Students_Table Students_Table { get; set; }
    }
}
