//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Courses_Table
    {
        public int S_courses_Id { get; set; }
        public int S_courses { get; set; }
    }
}
