//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students_Table()
        {
            this.Registerd_courses_Table = new HashSet<Registerd_courses_Table>();
        }
    
        public int std_id { get; set; }
        public string registration_id { get; set; }
        public string registration_number_ { get; set; }
        public string name_ { get; set; }
        public string email_ { get; set; }
        public string cell_number_ { get; set; }
        public int degree_program_id { get; set; }
    
        public virtual degree_programs degree_programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registerd_courses_Table> Registerd_courses_Table { get; set; }
    }
}
