//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_try_lv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher_Table()
        {
            this.Offerd_course_table = new HashSet<Offerd_course_table>();
        }
    
        public int Teacher_Id { get; set; }
        public string Employe_ID_ { get; set; }
        public string Name_ { get; set; }
        public string Email { get; set; }
        public string Cell_Number_ { get; set; }
        public int Department_ID { get; set; }
    
        public virtual Department_Table Department_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offerd_course_table> Offerd_course_table { get; set; }
    }
}
