//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPaper.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class registerd_crs_Table
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int reg_crs_Id { get; set; }
        public int std_id { get; set; }
        public int offer_crs_id { get; set; }
        public string status { get; set; }
    
        public virtual offerd_courseTable offerd_courseTable { get; set; }
        public virtual studentsTable studentsTable { get; set; }
    }
}
