//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studentsTable()
        {
            this.registerd_crs_Table = new HashSet<registerd_crs_Table>();
        }
    
        public int std_Id { get; set; }
        public string std_name { get; set; }
        public string std_deprt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registerd_crs_Table> registerd_crs_Table { get; set; }
    }
}
